/**
 * Read-only palette surface: display + run, no mutation.
 *
 * A read-only consumer (predefined layout, `editable: false`) imports only
 * this barrel: the `Palette` runtime, tool/spec resolution, keys, layout
 * display helpers, editor resolution, the command-box **run** model, and the
 * headless presenters. Nothing here can mutate a layout.
 *
 * `edition` (`./edition.svelte`) re-exports this barrel and adds the mutation
 * surface.
 */

export {
	handlePaletteCommandBoxInputKeydown,
	handlePaletteCommandChipKeydown,
	type PaletteCommandBoxEntry,
	type PaletteCommandBoxKeywordSuggestion,
	type PaletteCommandBoxModel,
	type PaletteCommandBoxQuery,
	paletteCommandBoxModel,
	paletteCommandEntries,
	paletteEnumSubsetValues,
	setPaletteCommandBoxInput,
} from './command-box.svelte'
export {
	type ConsoleMode,
	type ConsoleState,
	closeConsole,
	consoleState,
	consoleTool,
	openConsole,
	toggleConsole,
} from './console.svelte'
export {
	createPaletteKeys,
	isPaletteKeys,
	normalizePaletteKeystroke,
	paletteKeystrokeFromEvent,
} from './keys'
export {
	clampUnit,
	draggingEmptiesTrackIndex,
	isEditableTarget,
	type PaletteOrientation,
	paletteRoot,
	regionDirection,
} from './layout.svelte'
export {
	describePaletteItemConfiguration,
	hasPaletteItemTool,
	hydratePaletteLayout,
	isEditableTool,
	isRunTool,
	isStatusTool,
	Palette,
	PaletteError,
	type PaletteValueAction,
	type PaletteValueActions,
	paletteDefaultEditorCapabilities,
	paletteEnumValueKeywords,
	paletteTool,
	paletteToolFamily,
	renderPaletteEditor,
	resolvePaletteEditor,
	serializePaletteLayout,
	surfaceContextFromScope,
	validatePaletteLayout,
	valueActions,
	valueReader,
} from './palette.svelte'
export {
	type ButtonPresenter,
	buttonPresenter,
	type CommandBoxPresenter,
	type ConfiguratorPresenter,
	commandBoxPresenter,
	configuratorPresenter,
	type HeadChoiceDisplay,
	type HeadEnumSubsetConfig,
	type HeadItemConfigBase,
	headLayoutFromSurface,
	headMeta,
	headRegionFromScope,
	headTooltip,
	type SelectOption,
	type SelectPresenter,
	type SliderPresenter,
	type StatusPresenter,
	selectPresenter,
	sliderPresenter,
	statusPresenter,
	type TogglePresenter,
	togglePresenter,
} from './presenters.svelte'
export type {
	PaletteAnyTool,
	PaletteBase,
	PaletteBorder,
	PaletteBorders,
	PaletteComponentProps,
	PaletteConfig,
	PaletteConfiguratorComponent,
	PaletteConfiguredItemTarget,
	PaletteDragging,
	PaletteDrawerState,
	PaletteDrawerToolbarItem,
	PaletteEditableTool,
	PaletteEditableToolByFamily,
	PaletteEditableToolByFamilyOf,
	PaletteEditableToolOf,
	PaletteEditorCapability,
	PaletteEditorChoice,
	PaletteEditorComponent,
	PaletteEditorConfigs,
	PaletteEditorContext,
	PaletteEditorFamilyRegistry,
	PaletteEditorFlags,
	PaletteEditorFootprint,
	PaletteEditorOnlyItem,
	PaletteEditorOnlyRegistry,
	PaletteEditorOnlyToolbarItem,
	PaletteEditorRegistry,
	PaletteEditorSpec,
	PaletteIcon,
	PaletteItem,
	PaletteItemBindingSection,
	PaletteItemConfigurationDescriptor,
	PaletteItemMoveContract,
	PaletteItemPresentationSection,
	PaletteItemStructureSection,
	PaletteKeyBindings,
	PaletteKeys,
	PaletteKeystroke,
	PaletteOf,
	PaletteRegion,
	PaletteSchema,
	PaletteScope,
	PaletteStatusTool,
	PaletteSurfaceAxis,
	PaletteSurfaceContext,
	PaletteTool,
	PaletteToolBool,
	PaletteToolByFamily,
	PaletteToolByFamilyOf,
	PaletteToolbar,
	PaletteToolbarItem,
	PaletteToolbarItemBase,
	PaletteToolbarItemByEditor,
	PaletteToolEdit,
	PaletteToolEnum,
	PaletteToolEnumValue,
	PaletteToolFamily,
	PaletteToolFamilyOf,
	PaletteToolId,
	PaletteToolItem,
	PaletteToolNumber,
	PaletteToolOf,
	PaletteToolRun,
	PaletteToolSpec,
	PaletteToolStatus,
	PaletteTools,
	PaletteToolToolbarItem,
	PaletteTrack,
	SerializedPaletteLayout,
} from './types'
