/**
 * Single entry point for the headless palette system.
 *
 * Re-exports the public API surface of `@sursaut/ui/palette`
 * (`ui/src/palette/index.ts`) adapted for Svelte 5.
 */

export {
	handlePaletteCommandBoxInputKeydown,
	handlePaletteCommandChipKeydown,
	PALETTE_CATALOG_DRAG_MIME,
	type PaletteAddItemCommandEntry,
	type PaletteAddItemSource,
	type PaletteCatalogDragPayload,
	type PaletteCatalogDragSpecPayload,
	type PaletteCatalogDragVariantPayload,
	type PaletteCommandBoxEntry,
	type PaletteCommandBoxKeywordSuggestion,
	type PaletteCommandBoxModel,
	type PaletteCommandBoxQuery,
	type PaletteDerivedVariant,
	paletteAddItemEntries,
	paletteCatalogEntries,
	paletteCommandBoxModel,
	paletteCommandEntries,
	paletteDerivedVariants,
	paletteEnumSubsetValues,
	paletteToolbarItemFromCatalogPayload,
	parsePaletteCatalogDragPayload,
	serializePaletteCatalogDragPayload,
	setPaletteCommandBoxInput,
} from './command-box.svelte'
export { createPaletteKeys, normalizePaletteKeystroke, paletteKeystrokeFromEvent } from './keys'
export {
	actualTrackSpaceAt,
	beginPaletteCatalogInsertDrag,
	clampUnit,
	insertToolbar,
	insertTrackWithToolbar,
	isEditableTarget,
	type PaletteDragOrigin,
	type PaletteDragTarget,
	type PaletteItemDragTarget,
	type PaletteOrientation,
	type PaletteStackSpace,
	type PaletteToolbarDrag,
	type PaletteToolbarSpace,
	type PaletteTrackSpace,
	paletteItemDrag,
	paletteItemShield,
	paletteRoot,
	paletteStackSpace,
	paletteToolbarDrag,
	paletteToolbarSpace,
	paletteTrackSpace,
	regionDirection,
	removeEmptyTrack,
	removeToolbar,
	resizeToolbar,
} from './layout.svelte'
export {
	clearPaletteCatalogDragOnNativeDragEnd,
	getPaletteScope,
	hasPaletteItemTool,
	hydratePaletteLayout,
	isEditableTool,
	isEditing,
	isRunTool,
	notifyPaletteCatalogNativeDragStarted,
	Palette,
	PaletteError,
	type PaletteValueAction,
	type PaletteValueActions,
	paletteDefaultEditorCapabilities,
	paletteEnumValueKeywords,
	palettes,
	paletteTool,
	paletteToolFamily,
	renderPaletteConfigurator,
	renderPaletteEditor,
	resolveItemPlacementTarget,
	resolvePaletteEditor,
	serializePaletteLayout,
	setPaletteScope,
	surfaceContextFromScope,
	validatePaletteLayout,
	valueActions,
	valueReader,
} from './palette.svelte'
export type {
	PaletteAnyTool,
	PaletteBase,
	PaletteBorder,
	PaletteBorders,
	PaletteComponentProps,
	PaletteConfig,
	PaletteConfiguratorComponent,
	PaletteConfiguredItemTarget,
	PaletteDragging,
	PaletteDrawerState,
	PaletteDrawerToolbarItem,
	PaletteEditableTool,
	PaletteEditableToolByFamily,
	PaletteEditableToolByFamilyOf,
	PaletteEditableToolOf,
	PaletteEditorCapability,
	PaletteEditorChoice,
	PaletteEditorComponent,
	PaletteEditorConfigs,
	PaletteEditorContext,
	PaletteEditorFamilyRegistry,
	PaletteEditorFlags,
	PaletteEditorFootprint,
	PaletteEditorOnlyItem,
	PaletteEditorOnlyRegistry,
	PaletteEditorOnlyToolbarItem,
	PaletteEditorRegistry,
	PaletteEditorSpec,
	PaletteIcon,
	PaletteItem,
	PaletteItemBindingSection,
	PaletteItemConfigurationDescriptor,
	PaletteItemMoveContract,
	PaletteItemPresentationSection,
	PaletteItemStructureSection,
	PaletteKeyBindings,
	PaletteKeys,
	PaletteKeystroke,
	PaletteOf,
	PaletteRegion,
	PaletteSchema,
	PaletteScope,
	PaletteSurfaceAxis,
	PaletteSurfaceContext,
	PaletteTool,
	PaletteToolBool,
	PaletteToolByFamily,
	PaletteToolByFamilyOf,
	PaletteToolbar,
	PaletteToolbarItem,
	PaletteToolbarItemBase,
	PaletteToolbarItemByEditor,
	PaletteToolEdit,
	PaletteToolEnum,
	PaletteToolEnumValue,
	PaletteToolFamily,
	PaletteToolFamilyOf,
	PaletteToolId,
	PaletteToolItem,
	PaletteToolNumber,
	PaletteToolOf,
	PaletteToolRun,
	PaletteToolSpec,
	PaletteToolStatus,
	PaletteTools,
	PaletteToolToolbarItem,
	PaletteTrack,
	SerializedPaletteLayout,
} from './types'
